### ISSUE TITLE
Plugin support for Hearthstone and Heroes of the Storm?

### ISSUE THREAD

**Issue by ericvalente** [diegonc/packet-bnetp#7]
Are these in the works?  Thanks!

**Comment by diegonc** [comment]
No, not really.

To be honest, nothing has been added to this plugin during the past few years (4 I think). I just have been following Wireshark's evolution by adjusting the code from time to time.

Also, I'm not a Blizzard's protocols guru. I just wrote the core of the plugin and a script to parse the documentation located at [BNetDocs Redux](https://bnetdocs.org/) and generate the descriptions required by the core.

If the protocols used by those applications are already documented somewhere, maybe a script could be written to quickly add support for them. However, it would be required that the packets have the structure of BNCS or Warcraft III Game Protocol (i.e. a fixed byte for the protocol identification, a message id, a size and message data) for that process to work smoothly without having to apply major extensions to the core.
